CREATE TABLE legal_categories (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  parent_id uuid REFERENCES legal_categories(id),
  name_ru text NOT NULL,
  name_kk text NOT NULL,
  name_en text NOT NULL,
  description_ru text NOT NULL,
  description_kk text NOT NULL,
  description_en text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  high_risk boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  required_fact_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  required_document_rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  clarification_question_templates jsonb NOT NULL DEFAULT '[]'::jsonb,
  default_legal_route text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE case_classifications (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_id uuid REFERENCES legal_cases(id) ON DELETE SET NULL,
  conversation_id text,
  input_message_id uuid REFERENCES messages(id) ON DELETE SET NULL,
  owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  language text NOT NULL,
  jurisdiction text NOT NULL CHECK (jurisdiction = 'KZ'),
  category_code text NOT NULL,
  subcategory_code text NOT NULL,
  confidence numeric(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  alternatives jsonb NOT NULL DEFAULT '[]'::jsonb,
  facts jsonb NOT NULL DEFAULT '{}'::jsonb,
  missing_facts jsonb NOT NULL DEFAULT '[]'::jsonb,
  clarification_questions jsonb NOT NULL DEFAULT '[]'::jsonb,
  risk_level text NOT NULL,
  risk_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  urgency text NOT NULL,
  complexity text NOT NULL,
  model_provider text NOT NULL,
  model_id text NOT NULL,
  prompt_version text NOT NULL,
  user_confirmed boolean NOT NULL DEFAULT false,
  user_overridden boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  confirmed_at timestamptz
);

CREATE TABLE classification_feedback (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  classification_id uuid NOT NULL REFERENCES case_classifications(id) ON DELETE CASCADE,
  owner_user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source text NOT NULL CHECK (source IN ('user', 'expert')),
  corrected_category_code text NOT NULL,
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX case_classifications_case_idx ON case_classifications(case_id, created_at);
CREATE INDEX classification_feedback_classification_idx ON classification_feedback(classification_id);

INSERT INTO legal_categories (code, name_ru, name_kk, name_en, description_ru, description_kk, description_en, high_risk, sort_order, default_legal_route)
VALUES
  ('family', 'Семейные споры', 'Отбасы даулары', 'Family disputes', 'Семейные споры', 'Отбасы даулары', 'Family disputes', false, 10, 'civil'),
  ('labor', 'Трудовые споры', 'Еңбек даулары', 'Labor disputes', 'Трудовые споры', 'Еңбек даулары', 'Labor disputes', false, 20, 'civil'),
  ('civil.debt', 'Взыскание задолженности', 'Берешекті өндіру', 'Debt recovery', 'Взыскание задолженности', 'Берешекті өндіру', 'Debt recovery', false, 30, 'civil'),
  ('civil.contract', 'Договорные споры', 'Шарттық даулар', 'Contract disputes', 'Договорные споры', 'Шарттық даулар', 'Contract disputes', false, 40, 'civil'),
  ('consumer', 'Защита прав потребителей', 'Тұтынушы құқығын қорғау', 'Consumer protection', 'Защита прав потребителей', 'Тұтынушы құқығын қорғау', 'Consumer protection', false, 50, 'civil'),
  ('housing', 'Жилищные споры', 'Тұрғын үй даулары', 'Housing disputes', 'Жилищные споры', 'Тұрғын үй даулары', 'Housing disputes', false, 60, 'civil'),
  ('inheritance', 'Наследственные споры', 'Мұрагерлік даулар', 'Inheritance disputes', 'Наследственные споры', 'Мұрагерлік даулар', 'Inheritance disputes', false, 70, 'civil'),
  ('administrative', 'Административные обращения', 'Әкімшілік өтініштер', 'Administrative matters', 'Административные обращения', 'Әкімшілік өтініштер', 'Administrative matters', false, 80, 'administrative'),
  ('enforcement', 'Исполнительное производство', 'Атқарушылық іс жүргізу', 'Enforcement proceedings', 'Исполнительное производство', 'Атқарушылық іс жүргізу', 'Enforcement proceedings', false, 90, 'enforcement'),
  ('banking', 'Банковские и финансовые споры', 'Банк және қаржы даулары', 'Banking and finance', 'Банковские и финансовые споры', 'Банк және қаржы даулары', 'Banking and finance', false, 100, 'civil'),
  ('business', 'Предпринимательские споры', 'Кәсіпкерлік даулар', 'Business disputes', 'Предпринимательские споры', 'Кәсіпкерлік даулар', 'Business disputes', false, 110, 'civil'),
  ('personal_data', 'Персональные данные', 'Дербес деректер', 'Personal data', 'Персональные данные', 'Дербес деректер', 'Personal data', false, 120, 'administrative'),
  ('criminal_high_risk', 'Высокорисковые ситуации', 'Жоғары тәуекел жағдайлары', 'High-risk matters', 'Высокорисковые ситуации', 'Жоғары тәуекел жағдайлары', 'High-risk matters', true, 130, 'criminal_high_risk'),
  ('clarification_required', 'Требуется уточнение', 'Нақтылау қажет', 'Clarification required', 'Требуется уточнение', 'Нақтылау қажет', 'Clarification required', false, 999, 'manual_review')
ON CONFLICT (code) DO NOTHING;

INSERT INTO legal_categories (code, parent_id, name_ru, name_kk, name_en, description_ru, description_kk, description_en, high_risk, sort_order, required_fact_schema, clarification_question_templates, default_legal_route)
SELECT item.code, parent.id, item.name_ru, item.name_kk, item.name_en, item.name_ru, item.name_kk, item.name_en, item.high_risk, item.sort_order, item.required_fact_schema::jsonb, item.questions::jsonb, item.route
FROM (
  VALUES
    ('family.alimony.child','family','Взыскание алиментов на ребёнка','Балаға алимент өндіру','Child support',false,11,'{"fields":["child_birth_date","debtor_identity","income_info"]}','[]','civil'),
    ('family.alimony.spouse','family','Содержание супруга','Жұбайын асырау','Spousal support',false,12,'{"fields":["marriage_status","need_basis"]}','[]','civil'),
    ('family.alimony.adult_student','family','Алименты совершеннолетнему учащемуся','Кәмелетке толған студентке алимент','Adult student support',false,13,'{"fields":["education_document"]}','[]','civil'),
    ('family.divorce','family','Расторжение брака','Некені бұзу','Divorce',false,14,'{"fields":["marriage_date","children"]}','[]','civil'),
    ('family.property_division','family','Раздел имущества супругов','Ерлі-зайыптылар мүлкін бөлу','Marital property division',false,15,'{"fields":["property_list","acquisition_date"]}','[]','civil'),
    ('family.paternity','family','Установление отцовства','Әкелікті анықтау','Paternity',false,16,'{"fields":["child_data","alleged_parent"]}','[]','civil'),
    ('family.child_residence','family','Место жительства ребёнка','Баланың тұрғылықты жері','Child residence',false,17,'{"fields":["child_age","current_residence"]}','[]','civil'),
    ('family.child_communication','family','Порядок общения с ребёнком','Баламен араласу тәртібі','Child contact',false,18,'{"fields":["current_contact"]}','[]','civil'),
    ('family.parental_rights','family','Родительские права','Ата-ана құқықтары','Parental rights',true,19,'{"fields":["risk_to_child"]}','[]','civil'),
    ('family.other','family','Иной семейный спор','Өзге отбасылық дау','Other family dispute',false,20,'{"fields":["family_relation"]}','[]','civil'),
    ('labor.dismissal_reinstatement','labor','Незаконное увольнение','Заңсыз жұмыстан шығару','Wrongful dismissal',false,21,'{"fields":["dismissal_date","employer"]}','[]','civil'),
    ('labor.wage_arrears','labor','Невыплата зарплаты','Жалақы төлемеу','Wage arrears',false,22,'{"fields":["employment_period","amount"]}','[]','civil'),
    ('labor.leave_compensation','labor','Компенсация отпуска','Демалыс өтемақысы','Leave compensation',false,23,'{"fields":["employment_period"]}','[]','civil'),
    ('labor.workplace_injury','labor','Травма на работе','Өндірістік жарақат','Workplace injury',true,24,'{"fields":["injury_date","medical_docs"]}','[]','civil'),
    ('labor.disciplinary_action','labor','Дисциплинарное взыскание','Тәртіптік жаза','Disciplinary action',false,25,'{"fields":["order_date"]}','[]','civil'),
    ('labor.other','labor','Иной трудовой спор','Өзге еңбек дауы','Other labor dispute',false,26,'{"fields":["employer"]}','[]','civil'),
    ('civil.debt.loan','civil.debt','Долг по расписке или займу','Қарызхат немесе қарыз бойынша берешек','Loan debt',false,31,'{"fields":["loan_date","amount","debtor_identity"]}','[]','civil'),
    ('civil.debt.contract','civil.debt','Долг по договору','Шарт бойынша берешек','Contract debt',false,32,'{"fields":["contract_date","amount"]}','[]','civil'),
    ('civil.debt.unjust_enrichment','civil.debt','Неосновательное обогащение','Негізсіз баю','Unjust enrichment',false,33,'{"fields":["transfer_date","amount"]}','[]','civil'),
    ('civil.debt.other','civil.debt','Иная задолженность','Өзге берешек','Other debt',false,34,'{"fields":["basis","amount","debtor_identity"]}','[]','civil'),
    ('civil.contract.sale','civil.contract','Купля-продажа','Сатып алу-сату','Sale contract',false,41,'{"fields":["contract_date","item"]}','[]','civil'),
    ('civil.contract.services','civil.contract','Услуги','Қызметтер','Services',false,42,'{"fields":["service_terms"]}','[]','civil'),
    ('civil.contract.work','civil.contract','Подряд и ремонт','Мердігерлік және жөндеу','Work contract',false,43,'{"fields":["contract_or_receipt","paid_amount"]}','[]','civil'),
    ('civil.contract.supply','civil.contract','Поставка','Жеткізу','Supply',false,44,'{"fields":["contract_date","delivery_terms"]}','[]','civil'),
    ('civil.contract.lease','civil.contract','Аренда','Жалдау','Lease',false,45,'{"fields":["lease_period","rent_amount"]}','[]','civil'),
    ('civil.contract.construction','civil.contract','Строительство','Құрылыс','Construction',false,46,'{"fields":["contract_date","work_scope"]}','[]','civil'),
    ('civil.contract.other','civil.contract','Иной договорный спор','Өзге шарттық дау','Other contract dispute',false,47,'{"fields":["contract_basis"]}','[]','civil'),
    ('consumer.goods','consumer','Бракованный товар','Ақаулы тауар','Defective goods',false,51,'{"fields":["purchase_date","receipt"]}','[]','civil'),
    ('consumer.services','consumer','Некачественная услуга','Сапасыз қызмет','Poor service',false,52,'{"fields":["service_date"]}','[]','civil'),
    ('consumer.refund','consumer','Возврат денег','Ақшаны қайтару','Refund',false,53,'{"fields":["payment_proof"]}','[]','civil'),
    ('consumer.warranty','consumer','Гарантия','Кепілдік','Warranty',false,54,'{"fields":["warranty_card"]}','[]','civil'),
    ('consumer.other','consumer','Иной потребительский спор','Өзге тұтынушылық дау','Other consumer matter',false,55,'{"fields":["seller"]}','[]','civil'),
    ('housing.eviction','housing','Выселение','Үйден шығару','Eviction',true,61,'{"fields":["housing_basis","notice_date"]}','[]','civil'),
    ('housing.ownership','housing','Право собственности на жильё','Тұрғын үйге меншік құқығы','Housing ownership',false,62,'{"fields":["property_docs"]}','[]','civil'),
    ('housing.rent','housing','Аренда жилья','Тұрғын үйді жалдау','Housing rent',false,63,'{"fields":["lease_period"]}','[]','civil'),
    ('housing.utilities','housing','Коммунальные услуги','Коммуналдық қызметтер','Utilities',false,64,'{"fields":["invoice_period"]}','[]','civil'),
    ('housing.condominium','housing','ОСИ/КСК/кондоминиум','ОСИ/ПИК/кондоминиум','Condominium',false,65,'{"fields":["building_address"]}','[]','civil'),
    ('housing.other','housing','Иной жилищный спор','Өзге тұрғын үй дауы','Other housing dispute',false,66,'{"fields":["housing_basis"]}','[]','civil'),
    ('inheritance.acceptance_deadline','inheritance','Восстановление срока наследства','Мұраны қабылдау мерзімін қалпына келтіру','Inheritance deadline',false,71,'{"fields":["death_date","reason_for_delay"]}','[]','civil'),
    ('inheritance.division','inheritance','Раздел наследства','Мұраны бөлу','Inheritance division',false,72,'{"fields":["estate_list"]}','[]','civil'),
    ('inheritance.will','inheritance','Завещание','Өсиет','Will dispute',false,73,'{"fields":["will_date"]}','[]','civil'),
    ('inheritance.heir_recognition','inheritance','Признание наследником','Мұрагер деп тану','Heir recognition',false,74,'{"fields":["kinship_proof"]}','[]','civil'),
    ('inheritance.other','inheritance','Иной наследственный спор','Өзге мұрагерлік дау','Other inheritance dispute',false,75,'{"fields":["estate_basis"]}','[]','civil'),
    ('administrative.state_body_action','administrative','Действие госоргана','Меморган әрекеті','State body action',false,81,'{"fields":["action_date","state_body"]}','[]','administrative'),
    ('administrative.state_body_inaction','administrative','Бездействие госоргана','Меморган әрекетсіздігі','State body inaction',false,82,'{"fields":["application_date","state_body"]}','[]','administrative'),
    ('administrative.fine','administrative','Административный штраф','Әкімшілік айыппұл','Administrative fine',false,83,'{"fields":["fine_date"]}','[]','administrative'),
    ('administrative.e_otinish','administrative','e-Otinish обращение','e-Otinish өтініші','e-Otinish',false,84,'{"fields":["application_number"]}','[]','administrative'),
    ('administrative.other','administrative','Иное административное обращение','Өзге әкімшілік өтініш','Other administrative matter',false,85,'{"fields":["state_body"]}','[]','administrative'),
    ('enforcement.bailiff_inaction','enforcement','Бездействие ЧСИ','ЖСО әрекетсіздігі','Bailiff inaction',false,91,'{"fields":["enforcement_case_number"]}','[]','enforcement'),
    ('enforcement.seizure','enforcement','Арест имущества или счета','Мүлікке немесе шотқа тыйым','Seizure',false,92,'{"fields":["seizure_date"]}','[]','enforcement'),
    ('enforcement.installment','enforcement','Рассрочка исполнения','Орындауды бөліп төлеу','Installment of enforcement',false,93,'{"fields":["court_decision"]}','[]','enforcement'),
    ('enforcement.alimony_debt','enforcement','Задолженность по алиментам','Алимент берешегі','Alimony enforcement debt',false,94,'{"fields":["debt_amount"]}','[]','enforcement'),
    ('enforcement.other','enforcement','Иной исполнительный вопрос','Өзге атқарушылық мәселе','Other enforcement matter',false,95,'{"fields":["enforcement_case_number"]}','[]','enforcement'),
    ('banking.loan','banking','Банковский кредит','Банк кредиті','Bank loan',false,101,'{"fields":["loan_date"]}','[]','civil'),
    ('banking.microfinance','banking','Спор с МФО','МҚҰ дауы','MFI dispute',false,102,'{"fields":["loan_date","amount"]}','[]','civil'),
    ('banking.collection','banking','Коллекторы','Коллекторлар','Collections',true,103,'{"fields":["collector_name"]}','[]','civil'),
    ('banking.insurance','banking','Финансовое страхование','Қаржылық сақтандыру','Financial insurance',false,104,'{"fields":["policy_number"]}','[]','civil'),
    ('banking.ombudsman','banking','Банковский омбудсмен','Банк омбудсманы','Banking ombudsman',false,105,'{"fields":["bank_response"]}','[]','civil'),
    ('banking.other','banking','Иной банковский спор','Өзге банк дауы','Other banking dispute',false,106,'{"fields":["financial_provider"]}','[]','civil'),
    ('business.corporate','business','Корпоративный спор','Корпоративтік дау','Corporate dispute',false,111,'{"fields":["company_name"]}','[]','civil'),
    ('business.partner_dispute','business','Спор партнёров','Серіктестер дауы','Partner dispute',false,112,'{"fields":["agreement"]}','[]','civil'),
    ('business.commercial_debt','business','Коммерческая задолженность','Коммерциялық берешек','Commercial debt',false,113,'{"fields":["contract_date","amount"]}','[]','civil'),
    ('business.tax','business','Налоговый спор бизнеса','Бизнес салық дауы','Business tax dispute',false,114,'{"fields":["tax_notice"]}','[]','administrative'),
    ('business.other','business','Иной предпринимательский спор','Өзге кәсіпкерлік дау','Other business dispute',false,115,'{"fields":["business_role"]}','[]','civil'),
    ('personal_data.unlawful_processing','personal_data','Незаконная обработка данных','Деректерді заңсыз өңдеу','Unlawful data processing',true,121,'{"fields":["processor"]}','[]','administrative'),
    ('personal_data.disclosure','personal_data','Раскрытие персональных данных','Дербес деректерді жариялау','Personal data disclosure',true,122,'{"fields":["publication_source"]}','[]','administrative'),
    ('personal_data.deletion','personal_data','Удаление персональных данных','Дербес деректерді жою','Personal data deletion',false,123,'{"fields":["processor"]}','[]','administrative'),
    ('personal_data.other','personal_data','Иной спор по персональным данным','Өзге дербес деректер дауы','Other personal data matter',false,124,'{"fields":["processor"]}','[]','administrative'),
    ('criminal_high_risk.detention','criminal_high_risk','Задержание','Ұстау','Detention',true,131,'{"fields":["detention_time","location"]}','[]','criminal_high_risk'),
    ('criminal_high_risk.suspect_accused','criminal_high_risk','Подозреваемый или обвиняемый','Күдікті немесе айыпталушы','Suspect or accused',true,132,'{"fields":["case_stage"]}','[]','criminal_high_risk'),
    ('criminal_high_risk.victim','criminal_high_risk','Потерпевший','Жәбірленуші','Victim',true,133,'{"fields":["incident_date"]}','[]','criminal_high_risk'),
    ('criminal_high_risk.fraud','criminal_high_risk','Мошенничество','Алаяқтық','Fraud',true,134,'{"fields":["incident_date","amount"]}','[]','criminal_high_risk'),
    ('criminal_high_risk.domestic_violence','criminal_high_risk','Домашнее насилие','Тұрмыстық зорлық-зомбылық','Domestic violence',true,135,'{"fields":["immediate_safety","police_report"]}','[]','criminal_high_risk'),
    ('criminal_high_risk.other','criminal_high_risk','Иная высокорисковая ситуация','Өзге жоғары тәуекел жағдайы','Other high-risk matter',true,136,'{"fields":["immediate_risk"]}','[]','criminal_high_risk'),
    ('clarification_required.other','clarification_required','Нужны уточнения','Нақтылау керек','Needs clarification',false,1000,'{"fields":["parties","goal","documents"]}','[]','manual_review')
) AS item(code, parent_code, name_ru, name_kk, name_en, high_risk, sort_order, required_fact_schema, questions, route)
JOIN legal_categories parent ON parent.code = item.parent_code
ON CONFLICT (code) DO NOTHING;
